theme: jekyll-theme-slate
tittle: ¡Bienvenido a la página de inicio de setink!
description: No dudes de estar atento para nuevas actualizaciones
description: tenemos que tener paciencia para aprender 


